### ISSUE TITLE
Background removing effect

### ISSUE THREAD

**Issue by mnikitin** [bleakie/MaskInsightface#10]
Hello!

Have you estimated what is the effect of your input image normalization approach (face wrapping + background removing) on the final quality of recognition, compared to the conventional way of normalization (like insightface do, for instance) ?

Thank you!

**Comment by bleakie** [comment]
When the face is clear and the image quality is high, the effect of background removing is better.

**Comment by mnikitin** [comment]
Ok, thank you!
And what about quantitative results, have you done such comparison? Classification accuracy on some dataset before/after, for instance?

**Comment by bleakie** [comment]
mentioned above
