### ISSUE TITLE
关于人脸对齐

### ISSUE THREAD

**Issue by luameows** [bleakie/MaskInsightface#14]
按照我的理解，人脸对齐步骤如下
1.统计facial landmark相对检测框的坐标，求取平均脸的landmark坐标。
2.将landmark相对坐标转化为112x112或其他大小检测框的绝对坐标。
3.利用相似性变换计算待对齐人脸与标准脸的变换矩阵。

不知我上述理解是否有问题。这里面对于第二点，landmark相对坐标该如何转化到绝对坐标呢？按照步骤1的统计，绝对坐标是根据检测框大小求来的，但是针对不同姿态的人脸，检测框的宽高比可能就有很大变化，这样就应该没法直接套用112x112或112x96大小的人脸。

请问关于这一点，您有什么建议么？

**Comment by bleakie** [comment]
仿射变换就是对应两个矩阵的坐标进行变换，得到112x112或112x96不同的size需要不同的变换矩阵，参见[face_align_util.py](https://github.com/bleakie/MaskInsightface/blob/master/face_align_util.py)

**Comment by luameows** [comment]
感谢回复，可能我之前的表述有误。
现在我有一套自己的关键点检测网络，不同于mtcnn采用的眼睛中心，这里我们采用了每只眼的两个眼角。
在计算变换矩阵时，由于关键点不同，就无法采用通用的五点坐标。在这种情形下，我希望针对我当前的关键点，重新统计一套标准脸的关键点坐标。
请问，这种情况下我该如何统计呢，或者说[face_align_util.py](https://github.com/bleakie/MaskInsightface/blob/master/face_align_util.py)中的arcface_src是如何统计的呢？

**Comment by bleakie** [comment]
你可以按照平均正脸在112*112的坐标下找眼角的坐标，然后设置到转换矩阵中
