### ISSUE TITLE
关于训练数据

### ISSUE THREAD

**Issue by liuruqin001** [bleakie/MaskInsightface#16]
请问模型y2-res2-6-10-2-dim256与y2-res4-8-16-4-dim256是同样的数据集训练的吗，数据集是居于glint和私有数据训练，私有数据大概多少？我用单用glint数据训练，效果不太好，CFP_FP的识别率差

**Comment by bleakie** [comment]
是同一批数据训练的，可以基于我的模型作为预训练来fine-tune
