### ISSUE TITLE
请问静默活体做完了么?

### ISSUE THREAD

**Issue by yangjian1218** [bleakie/MaskInsightface#25]

**Comment by bleakie** [comment]
[CelebA-Spoof 数据怼进arcface里，效果够用](https://github.com/Davidzhangyuanhan/CelebA-Spoof)

**Comment by yangjian1218** [comment]
> [CelebA-Spoof 数据怼进arcface里，效果够用](https://github.com/Davidzhangyuanhan/CelebA-Spoof)
您训练过么?head部分你怎么改的? 是直接最后增加一层二分类么? 数据集要怎么处理? 直接resize么?

**Comment by bleakie** [comment]
resize到112*112，head部分增加了2分类，效果基本能满足需求
