### ISSUE TITLE
预训练模型下载地址失效

### ISSUE THREAD

**Issue by Ancho5515** [bleakie/MaskInsightface#3]

**Comment by bleakie** [comment]
See readme please.

**Comment by Ancho5515** [comment]
I have checked it again and the link in readme ([https://pan.baidu.com/s/1GTBJf71Axwjs_yo5klAm9Q](https://pan.baidu.com/s/1GTBJf71Axwjs_yo5klAm9Q)) is invalid.

**Comment by bleakie** [comment]
See here:  https://drive.google.com/drive/folders/1zWadm9yu0rcjIQ_MnoXAQ27kA-CJYGms?usp=sharing

**Comment by dingweichao123** [comment]
> I have checked it again and the link in readme (https://pan.baidu.com/s/1GTBJf71Axwjs_yo5klAm9Q) is invalid.

你好，请问你有下载到预训练模型吗？

**Comment by xsacha** [comment]
It says you need permission to access
