### ISSUE TITLE
预训练模型

### ISSUE THREAD

**Issue by dingweichao123** [bleakie/MaskInsightface#6]
预训练模型的下载链接没有开放权限啊，下载不了

**Comment by bleakie** [comment]
try again

**Comment by dingweichao123** [comment]
> try again

还是不行。。。

**Comment by bleakie** [comment]
尝试这个  https://pan.baidu.com/s/1ySZeJWa-r7oS4E_8dpdo4w 提取码: enph

**Comment by dingweichao123** [comment]
> 尝试这个 https://pan.baidu.com/s/1ySZeJWa-r7oS4E_8dpdo4w 提取码: enph

可以了，谢谢

**Comment by mnikitin** [comment]
@bleakie hello!
could you please provide non-baidu-disk link to pretrained model (resnet152) ? Google drive or dropbox are good options.
I have some issues with baidu account creating, so I can't download anything from baidu cloud disk.

Thank you!

**Comment by mnikitin** [comment]
@bleakie 
Could you please clarify what data preprocessing procedure was used to train resnet152 model? (this link: https://pan.baidu.com/s/1ySZeJWa-r7oS4E_8dpdo4w)

I tried to use this model with SSH+PRNet preprocessing (gen_datasets.py), but the results are poor. What is the correct way of preprocessing?
