### ISSUE TITLE
PRN模型读取错误

### ISSUE THREAD

**Issue by jiajiajun** [bleakie/MaskInsightface#8]
楼主您好，在运行gen_datasets.py时，出现prn模型读取错误（已从readme提供的百度网盘链接下载模型，并放入Data/nrt-data里边），请问您知道是什么原因吗？非常感谢！
代码：
self.pos_predictor = PosPrediction(self.resolution_inp, self.resolution_op)
        prn_path = os.path.join(prefix, 'Data/net-data/256_256_resfcn256_weight')
        if not os.path.isfile(prn_path + '.data-00000-of-00001'):
            print("please download PRN trained model first.") 
            exit()
        self.pos_predictor.restore(prn_path)

错误：
DataLossError (see above for traceback): Unable to open table file /home/../MaskInsightface/PRNet_Mask/Data/net-data/256_256_resfcn256_weight: Failed precondition: /../MaskInsightface/PRNet_Mask/Data/net-data/256_256_resfcn256_weight: perhaps your file is in a different file format and you need to use a different restore operator?

**Comment by jiajiajun** [comment]
不好意思，是x下载模型已放入Data/net-data里边

**Comment by jiajiajun** [comment]
不好意思，下载模型是放进了文件夹Data/net-data里边

**Comment by bleakie** [comment]
请参考下PRNet_Mask/api.py中PRN的初始化使用
